name: build

on: [push, pull_request]

jobs:
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        mkdir workspace
        cd workspace 
        git clone https://github.com/Holodome/holoc/
        cd holoc
    - name: osx-make-debug
      run: 
        make
